# Generated by Django 5.0.7 on 2024-07-26 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='car_type',
        ),
        migrations.RemoveField(
            model_name='featuredbooking',
            name='location',
        ),
    ]
