# Generated by Django 5.0.7 on 2024-07-27 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_booking_car_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredbooking',
            name='car_type',
        ),
    ]
